Repository civicrm/org.civicrm.api4, pull requests merged in 2019-05, with the labels that each got.

#124 Scan extension directories instead of include paths
  Civi/Api4/Action/Entity/Get.php
  Civi/Api4/Action/GetActions.php
  api4.php
Labels: master

#125 Allow Result class to be extended
  Civi/Api4/Generic/AbstractAction.php
  Civi/Api4/Generic/BasicReplaceAction.php
  Civi/Api4/Provider/ActionObjectProvider.php
  Civi/Api4/Result/ReplaceResult.php
  ang/api4Explorer/Explorer.js
Labels: master

#127 Add UFMatch entity
  Civi/Api4/UFMatch.php
Labels: master

#126 Add isCurrent filter trait
  Civi/Api4/Action/Relationship/Get.php
  Civi/Api4/Event/Subscriber/IsCurrentSubscriber.php
  Civi/Api4/Generic/Traits/IsCurrentTrait.php
  Civi/Api4/Relationship.php
  Civi/Api4/Utils/ReflectionUtils.php
  ang/api4Explorer/Explorer.html
  css/explorer.css
  tests/phpunit/Action/CurrentFilterTest.php
Labels: has-test, master

#130 Fixes #129 set correct type for custom date fields
  Civi/Api4/Service/Schema/Joinable/CustomGroupJoinable.php
  Civi/Api4/Service/Spec/SpecFormatter.php
  Civi/Api4/Service/Spec/SpecGatherer.php
Labels: master

#131 Explorer - don't parse date strings to js objects
  ang/api4Explorer/Explorer.js
Labels: master

#132 Better error handling of invalid joins.
  Civi/Api4/Query/Api4SelectQuery.php
  Civi/Api4/Service/Schema/Joinable/CustomGroupJoinable.php
  Civi/Api4/Service/Schema/Joinable/Joinable.php
Labels: master

#137 More thorough padding of getFields results
  Civi/Api4/Generic/BasicGetFieldsAction.php
Labels: master

#134 Support contact api_key field
  Civi/Api4/Action/Contact/GetFields.php
  Civi/Api4/Contact.php
  Civi/Api4/Generic/AbstractAction.php
  Civi/Api4/Generic/Traits/DAOActionTrait.php
  Civi/Api4/Query/Api4SelectQuery.php
  Civi/Api4/Service/Spec/SpecGatherer.php
  tests/phpunit/Action/ContactApiKeyTest.php
Labels: master

#136 Support contact api_key field
  Civi/Api4/Action/Contact/GetFields.php
  Civi/Api4/Contact.php
  Civi/Api4/Generic/AbstractAction.php
  Civi/Api4/Generic/Traits/DAOActionTrait.php
  Civi/Api4/Query/Api4SelectQuery.php
  tests/phpunit/Action/ContactApiKeyTest.php
Labels: 4.3

#135 Support contact api_key field
  Civi/Api4/Action/Contact/GetFields.php
  Civi/Api4/Contact.php
  Civi/Api4/Generic/AbstractAction.php
  Civi/Api4/Generic/Traits/DAOActionTrait.php
  Civi/Api4/Query/Api4SelectQuery.php
  tests/phpunit/Action/ContactApiKeyTest.php
Labels: 4.4

#138 Standardize delete results to be nested arrays
  Civi/Api4/Generic/DAODeleteAction.php
  tests/phpunit/Action/ReplaceTest.php
  tests/phpunit/Entity/ConformanceTest.php
  tests/phpunit/Entity/ParticipantTest.php
Labels: master

#140 ApiExplorer: fallback when field entity not declaired
  ang/api4Explorer/Explorer.js
Labels: master

#139 Add setting entity
  Civi/Api4/Action/GetActions.php
  Civi/Api4/Action/Setting/AbstractSettingAction.php
  Civi/Api4/Action/Setting/Get.php
  Civi/Api4/Action/Setting/GetFields.php
  Civi/Api4/Action/Setting/Revert.php
  Civi/Api4/Action/Setting/Set.php
  Civi/Api4/Event/Subscriber/ValidateFieldsSubscriber.php
  Civi/Api4/Generic/BasicGetFieldsAction.php
  Civi/Api4/Generic/Result.php
  Civi/Api4/Setting.php
  ang/api4Explorer/Explorer.html
  api4.php
  tests/phpunit/Entity/ConformanceTest.php
  tests/phpunit/Entity/SettingTest.php
Labels: master

#141 Add System api
  Civi/Api4/Action/System/Check.php
  Civi/Api4/Action/System/Flush.php
  Civi/Api4/Generic/BasicGetFieldsAction.php
  Civi/Api4/System.php
Labels: master

#142 Settings api to work with multiple domains
  Civi/Api4/Action/Setting/AbstractSettingAction.php
  Civi/Api4/Action/Setting/Get.php
  Civi/Api4/Action/Setting/Revert.php
  Civi/Api4/Action/Setting/Set.php
  Civi/Api4/Domain.php
  Civi/Api4/Generic/Result.php
  tests/phpunit/Entity/SettingTest.php
Labels: master

#143 Throw error when delete fails to find a record
  Civi/Api4/Generic/AbstractQueryAction.php
  Civi/Api4/Generic/DAODeleteAction.php
Labels: master

#144 Throw error when update fails
  Civi/Api4/Generic/AbstractQueryAction.php
  Civi/Api4/Generic/BasicUpdateAction.php
  Civi/Api4/Generic/DAOCreateAction.php
  Civi/Api4/Generic/DAOGetAction.php
  Civi/Api4/Generic/DAOUpdateAction.php
  tests/phpunit/DataSets/ConformanceTest.json
Labels: master

#145 Better handling of api_key
  Civi/Api4/Generic/Traits/DAOActionTrait.php
Labels: master

#146 Improve handling of contacts & related entities
  Civi/Api4/Generic/DAODeleteAction.php
  Civi/Api4/Generic/Traits/DAOActionTrait.php
  tests/phpunit/Action/ContactApiKeyTest.php
Labels: master

#148 Add campaign spec provider
  Civi/Api4/Service/Spec/Provider/CampaignCreationSpecProvider.php
Labels: master

#149 Retrieve bao instead of dao
  Civi/Api4/Generic/AbstractEntity.php
  Civi/Api4/Generic/Traits/DAOActionTrait.php
  Civi/Api4/Query/Api4SelectQuery.php
  Civi/Api4/Service/Spec/FieldSpec.php
  Civi/Api4/Service/Spec/Provider/ACLCreationSpecProvider.php
  Civi/Api4/Service/Spec/SpecGatherer.php
  Civi/Api4/Utils/CoreUtil.php
  tests/phpunit/Action/ContactApiKeyTest.php
Labels: master

#150 Fix address
  Civi/Api4/Action/Address/Create.php
  Civi/Api4/Action/Address/Update.php
  Civi/Api4/Generic/Traits/DAOActionTrait.php
  Civi/Api4/Service/Spec/Provider/UFMatchCreationSpecProvider.php
Labels: master

#151 Improve Domain entity
  Civi/Api4/Action/Domain/Get.php
  Civi/Api4/Domain.php
  Civi/Api4/Service/Spec/Provider/DomainCreationSpecProvider.php
Labels: master

#152 Add ContributionPage api
  Civi/Api4/ContributionPage.php
Labels: master

#153 Add statusPreference entity
  Civi/Api4/Service/Spec/Provider/StatusPreferenceCreationSpecProvider.php
  Civi/Api4/StatusPreference.php
Labels: master

#154 Add relationshipType spec for required fields
  Civi/Api4/Service/Spec/Provider/RelationshipTypeCreationSpecProvider.php
Labels: master

#155 Updates
  Civi/Api4/Event/Subscriber/IsCurrentSubscriber.php
  Civi/Api4/Generic/AbstractCreateAction.php
  Civi/Api4/Generic/Traits/IsCurrentTrait.php
Labels: master

#156 Allow creating option list when creating custom field
  Civi/Api4/Action/CustomField/Create.php
  Civi/Api4/CustomField.php
  Civi/Api4/Event/Subscriber/CustomFieldPreCreationSubscriber.php
  Civi/Api4/Generic/Traits/DAOActionTrait.php
  Civi/Api4/Service/Spec/FieldSpec.php
  Civi/Api4/Service/Spec/Provider/CustomFieldCreationSpecProvider.php
  Civi/Api4/Service/Spec/Provider/CustomGroupCreationSpecProvider.php
  tests/phpunit/Action/CreateCustomValueTest.php
  tests/phpunit/Action/CreateWithOptionGroupTest.php
  tests/phpunit/Spec/SpecGathererTest.php
Labels: master

#157 Improve Event api
  Civi/Api4/Action/Event/Create.php
  Civi/Api4/Event.php
  Civi/Api4/Generic/BasicGetFieldsAction.php
  Civi/Api4/Service/Spec/Provider/EventCreationSpecProvider.php
  tests/phpunit/Service/TestCreationParameterProvider.php
Labels: master

#158 Entity tag
  Civi/Api4/Service/Spec/Provider/AddressCreationSpecProvider.php
  Civi/Api4/Service/Spec/Provider/ContactCreationSpecProvider.php
  Civi/Api4/Service/Spec/Provider/ContactTypeCreationSpecProvider.php
  Civi/Api4/Service/Spec/Provider/EntityTagCreationSpecProvider.php
  Civi/Api4/Service/Spec/Provider/Generic/SpecProviderInterface.php
  Civi/Api4/Service/Spec/Provider/NoteCreationSpecProvider.php
  Civi/Api4/Service/Spec/Provider/TagCreationSpecProvider.php
  Civi/Api4/Service/Spec/SpecGatherer.php
Labels: master
